(* 目的 誕生日(月と日)を受け取ったら、星座を返す *)
(* seiza int int -> string *)
let seiza x y =
  if x = 3 then if y > 20 then "おひつじ" else "うお" 
           else if x = 4 then if y > 19 then "おうし" else "おひつじ"
           else if x = 5 then if y > 20 then "ふたご" else "おうし"
           else if x = 6 then if y > 21 then "かに" else "ふたご"
           else if x = 7 then if y > 22 then "しし" else "かに"
           else if x = 8 then if y > 22 then "おとめ" else "しし"
           else if x = 9 then if y > 22 then "てんびん" else "おとめ"
           else if x = 10 then if y > 23 then "さそり" else "てんびん"
           else if x = 11 then if y > 22 then "いて" else "さそり"
           else if x = 12 then if y > 21 then "やぎ" else "いて"
           else if x = 1 then if y > 19 then "みずがめ" else "やぎ"
           else if x = 2 then if y > 18 then "うお" else "みずがめ"
           else ""
(* test *)
let test1 = seiza 4 19 = "おひつじ"
let test2 = seiza 5 20 = "おうし" 
let test3 = seiza 6 21 = "ふたご"
let test4 = seiza 7 22 = "かに"
let test5 = seiza 8 22 = "しし"
let test6 = seiza 9 22 = "おとめ"
let test7 = seiza 10 23 = "てんびん"
let test8 = seiza 11 22 = "さそり"
let test9 = seiza 12 21 = "いて"
let test10 = seiza 1 19 = "やぎ"
let test11 = seiza 2 18 = "みずがめ"
let test12 = seiza 3 20 = "うお"
